### ISSUE TITLE
Fix user profile deletion problem

### ISSUE THREAD

**Issue by bibekdahal** [eoglethorpe/deep#142]
Patrice's profile is sometimes deleted automatically. Find the source of problem and solve it.

**Comment by eoglethorpe** [comment]
What was the fix?

**Comment by bibekdahal** [comment]
The user profile is set to store a reference to the "last event" the user selected. So when a user selected a event and delete that very event, the user profile, with django's default behavior, also got deleted.

I have changed this behavior to set the last_event to null if it gets deleted. This issue will be closed in the next commit.
