### ISSUE TITLE
Assessment registry - additional fields required

### ISSUE THREAD

**Issue by patricechataigner** [eoglethorpe/deep#470]
Please look into the following word document and add the fields in red to the current list of fields available in the assessment registry tagging screen.

cheers and hope you got back safe! 
[new fields assessment registry.docx](https://github.com/eoglethorpe/deep/files/1197791/new.fields.assessment.registry.docx)

**Comment by bibekdahal** [comment]
What will be options for the fields: crisis type, donors, coordination and sector?

Using #462 for options for unit of analysis and unit of reporting.

**Comment by patricechataigner** [comment]
Crisis types: Reuse the crisis list already available in the DEEP. Make the field single choice

Donors: Keep Field blank, one day we will have an entity panel and this will be easier.

Coordination: Three option, single choice: Uncoordinated, Harmonized or Joint

Sectors: This should be automatically calculated based on the number of sector selected below. So this is an automatic field.

All m ybest,





Patrice Chataigner
Senior Analyst
Email       pc@acaps.org<mailto:pc@acaps.org>
Direct      +41 22 338 15 97
Mobile    + 41 792 358 174
Skype:     pchataigner
Website  www.acaps.org

23, Avenue de France
CH-1202 Geneva
5th Floor

**Comment by bibekdahal** [comment]
So is the crisis type same as disaster type used in weekly reports ?

For sectors, is it the total number of sectors filled or is it it's percentage? Or, is there some other specific formula?

Thanks.

**Comment by patricechataigner** [comment]
Yes same crisis type as disaster type.

Total number of sectors filled. A simple count is ok, IF WASH food and health are selected, then the number should be 3.

Cheers!




Patrice Chataigner
Senior Analyst
Email       pc@acaps.org<mailto:pc@acaps.org>
Direct      +41 22 338 15 97
Mobile    + 41 792 358 174
Skype:     pchataigner
Website  www.acaps.org

23, Avenue de France
CH-1202 Geneva
5th Floor
