### ISSUE TITLE
Anomalies in excel export for custom frameworks

### ISSUE THREAD

**Issue by eoglethorpe** [eoglethorpe/deep#472]
Numerical value fields aren't appearing in export filter and the fields aren't present in excel export

**Comment by bibekdahal** [comment]
We have never implemented a filter for numerical value.

Should we add new type of filter? Should it be range filter or just filter by specific number?

We will add the number value in the export though.

**Comment by eoglethorpe** [comment]
i vote just add it to the export for now but in the re-write we should have a numerical filter

**Comment by patricechataigner** [comment]
agreed

Patrice Chataigner
Senior Analyst
Email       pc@acaps.org<mailto:pc@acaps.org>
Direct      +41 22 338 15 97
Mobile    + 41 792 358 174
Skype:     pchataigner
Website  www.acaps.org

23, Avenue de France
CH-1202 Geneva
5th Floor
