### ISSUE TITLE
Entries - Date of the information

### ISSUE THREAD

**Issue by patricechataigner** [eoglethorpe/deep#64]
I refer to the mock up in the dropbox in the word document about this screen. Sometimes the date of the information is different from the date of the lead, i.e. if a document from january 2016 says that the election have been postponed to June 2016. that s why it is important to have a date field in this screen.
The date field can appear below the map, and by default be the date of the lead. or it can appear at the level of each excerpt along the reliability, number and severity tag. 

Cheers!

**Comment by eoglethorpe** [comment]
+1 

Can we add a date value to each entry?
