### ISSUE TITLE
Lead screen - delete a lead entry

### ISSUE THREAD

**Issue by NNaddia** [eoglethorpe/deep#76]
I don't manage to delete a lead entry on the lead screen. I can delete entries on that particular lead on the entry screen but not the overall report/lead.

**Comment by bibekdahal** [comment]
You can find the delete button when you click and expand a lead.
![image](https://cloud.githubusercontent.com/assets/6505822/19180479/ce4925fa-8c85-11e6-85ee-6527395b59ad.png)
