### ISSUE TITLE
Entries - Save button

### ISSUE THREAD

**Issue by patricechataigner** [eoglethorpe/deep#93]
Is it possible to have different save buttons:
- save (and return to overview pages with entries). This one is already there
- save and add, while refreshing the entire tagg page, including geographical areas; affected groups, sectors and information attributes, excerpts already captured; etc.
- Save and add, clearing text excerpts, information attributes, affected groups, sectoral information, but keeping metadata geographic location, affected group, date ( you can embbeded a little map in the button to show the difference with the second button)

**Comment by bibekdahal** [comment]
The third option is not clear as to whether you want to clear "affected groups" or keep it.

**Comment by patricechataigner** [comment]
Yes sorry keep affected groups in the third option
